<?php

namespace Database\Seeders;

use App\Models\IsuRisiko;
use Illuminate\Database\Seeder;

class IsuRisikoSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            ['id_isu' => 'ISU0001', 'tarikh_isu' => '2025-10-02', 'id_pelaksana' => 'SPANA_003', 'id_syarikat' => 'SPTAN_010', 'kategori_isu' => 'Isu Pematuhan', 'butiran_isu' => 'Isu berkaitan isu pematuhan', 'tahap_risiko' => 'Kritikal', 'status' => 'Selesai', 'pic' => 'Yusof Majid', 'tindakan_diambil' => 'Tindakan susulan', 'tarikh_tindakan' => '2025-10-05', 'tarikh_tutup' => '2025-10-08', 'catatan' => 'Isu diselesaikan'],
            ['id_isu' => 'ISU0002', 'tarikh_isu' => '2025-10-21', 'id_pelaksana' => 'SPANA_002', 'id_syarikat' => 'SPTAN_008', 'kategori_isu' => 'Lain-lain', 'butiran_isu' => 'Isu berkaitan lain-lain', 'tahap_risiko' => 'Kritikal', 'status' => 'Baru', 'pic' => 'Nurul Rashid', 'tindakan_diambil' => null, 'tarikh_tindakan' => null, 'tarikh_tutup' => null, 'catatan' => 'Perlu pemantauan'],
            ['id_isu' => 'ISU0003', 'tarikh_isu' => '2025-09-14', 'id_pelaksana' => 'SPANA_002', 'id_syarikat' => 'SPTAN_008', 'kategori_isu' => 'Masalah Komunikasi', 'butiran_isu' => 'Isu berkaitan masalah komunikasi', 'tahap_risiko' => 'Tinggi', 'status' => 'Ditutup', 'pic' => 'Siti Latif', 'tindakan_diambil' => 'Tindakan susulan', 'tarikh_tindakan' => '2025-09-15', 'tarikh_tutup' => '2025-09-20', 'catatan' => 'Perlu pemantauan'],
            ['id_isu' => 'ISU0004', 'tarikh_isu' => '2025-10-08', 'id_pelaksana' => 'SPANA_004', 'id_syarikat' => 'SPTAN_003', 'kategori_isu' => 'Masalah Komunikasi', 'butiran_isu' => 'Isu berkaitan masalah komunikasi', 'tahap_risiko' => 'Sederhana', 'status' => 'Dalam Tindakan', 'pic' => 'Abdul Salleh', 'tindakan_diambil' => 'Tindakan susulan', 'tarikh_tindakan' => '2025-10-10', 'tarikh_tutup' => null, 'catatan' => 'Isu diselesaikan'],
            ['id_isu' => 'ISU0005', 'tarikh_isu' => '2025-09-20', 'id_pelaksana' => 'SPANA_003', 'id_syarikat' => 'SPTAN_003', 'kategori_isu' => 'Masalah Komunikasi', 'butiran_isu' => 'Isu berkaitan masalah komunikasi', 'tahap_risiko' => 'Kritikal', 'status' => 'Ditutup', 'pic' => 'Ali Abdullah', 'tindakan_diambil' => 'Tindakan susulan', 'tarikh_tindakan' => '2025-09-21', 'tarikh_tutup' => '2025-09-25', 'catatan' => null],
            ['id_isu' => 'ISU0006', 'tarikh_isu' => '2025-09-17', 'id_pelaksana' => 'SPANA_001', 'id_syarikat' => 'SPTAN_002', 'kategori_isu' => 'Lain-lain', 'butiran_isu' => 'Isu berkaitan lain-lain', 'tahap_risiko' => 'Kritikal', 'status' => 'Ditutup', 'pic' => 'Siti Ismail', 'tindakan_diambil' => 'Tindakan susulan', 'tarikh_tindakan' => '2025-09-20', 'tarikh_tutup' => '2025-09-25', 'catatan' => 'Isu diselesaikan'],
            ['id_isu' => 'ISU0007', 'tarikh_isu' => '2025-11-04', 'id_pelaksana' => 'SPANA_002', 'id_syarikat' => 'SPTAN_006', 'kategori_isu' => 'Bayaran Lewat', 'butiran_isu' => 'Isu berkaitan bayaran lewat', 'tahap_risiko' => 'Kritikal', 'status' => 'Baru', 'pic' => 'Ali Hassan', 'tindakan_diambil' => null, 'tarikh_tindakan' => null, 'tarikh_tutup' => null, 'catatan' => null],
            ['id_isu' => 'ISU0008', 'tarikh_isu' => '2025-09-24', 'id_pelaksana' => 'SPANA_001', 'id_syarikat' => 'SPTAN_009', 'kategori_isu' => 'Lain-lain', 'butiran_isu' => 'Isu berkaitan lain-lain', 'tahap_risiko' => 'Kritikal', 'status' => 'Selesai', 'pic' => 'Ibrahim Yusof', 'tindakan_diambil' => 'Tindakan susulan', 'tarikh_tindakan' => '2025-09-27', 'tarikh_tutup' => '2025-09-30', 'catatan' => 'Isu diselesaikan'],
            ['id_isu' => 'ISU0009', 'tarikh_isu' => '2025-10-25', 'id_pelaksana' => 'SPANA_004', 'id_syarikat' => 'SPTAN_006', 'kategori_isu' => 'Prestasi Lemah', 'butiran_isu' => 'Isu berkaitan prestasi lemah', 'tahap_risiko' => 'Sederhana', 'status' => 'Baru', 'pic' => 'Razak Taib', 'tindakan_diambil' => null, 'tarikh_tindakan' => null, 'tarikh_tutup' => null, 'catatan' => 'Isu diselesaikan'],
            ['id_isu' => 'ISU0010', 'tarikh_isu' => '2025-12-01', 'id_pelaksana' => 'SPANA_001', 'id_syarikat' => 'SPTAN_005', 'kategori_isu' => 'Isu Pematuhan', 'butiran_isu' => 'Isu berkaitan isu pematuhan', 'tahap_risiko' => 'Rendah', 'status' => 'Dalam Tindakan', 'pic' => 'Nadia Latif', 'tindakan_diambil' => 'Tindakan susulan', 'tarikh_tindakan' => '2025-12-02', 'tarikh_tutup' => null, 'catatan' => 'Perlu pemantauan'],
            ['id_isu' => 'ISU0011', 'tarikh_isu' => '2025-11-15', 'id_pelaksana' => 'SPANA_003', 'id_syarikat' => 'SPTAN_001', 'kategori_isu' => 'Kehadiran Rendah', 'butiran_isu' => 'Graduan kehadiran bawah 75% 2 bulan berturut', 'tahap_risiko' => 'Tinggi', 'status' => 'Dalam Tindakan', 'pic' => 'Ahmad Hassan', 'tindakan_diambil' => 'Notifikasi kepada mentor', 'tarikh_tindakan' => '2025-11-16', 'tarikh_tutup' => null, 'catatan' => null],
            ['id_isu' => 'ISU0012', 'tarikh_isu' => '2025-12-10', 'id_pelaksana' => 'SPANA_001', 'id_syarikat' => 'SPTAN_004', 'kategori_isu' => 'Logbook Lewat', 'butiran_isu' => 'Logbook belum dikemukakan selepas deadline', 'tahap_risiko' => 'Rendah', 'status' => 'Baru', 'pic' => 'Siti Aminah', 'tindakan_diambil' => null, 'tarikh_tindakan' => null, 'tarikh_tutup' => null, 'catatan' => null],
            ['id_isu' => 'ISU0013', 'tarikh_isu' => '2025-10-15', 'id_pelaksana' => 'SPANA_002', 'id_syarikat' => 'SPTAN_007', 'kategori_isu' => 'Bayaran Lewat', 'butiran_isu' => 'Bayaran elaun lewat lebih 7 hari', 'tahap_risiko' => 'Tinggi', 'status' => 'Selesai', 'pic' => 'Omar Ali', 'tindakan_diambil' => 'Bayaran segera diproses', 'tarikh_tindakan' => '2025-10-17', 'tarikh_tutup' => '2025-10-20', 'catatan' => 'Bayaran telah dibuat'],
            ['id_isu' => 'ISU0014', 'tarikh_isu' => '2025-11-22', 'id_pelaksana' => 'SPANA_004', 'id_syarikat' => 'SPTAN_009', 'kategori_isu' => 'Prestasi Lemah', 'butiran_isu' => 'Skor prestasi bawah 6 untuk 3 graduan', 'tahap_risiko' => 'Sederhana', 'status' => 'Dalam Tindakan', 'pic' => 'Zainab Hamid', 'tindakan_diambil' => 'Sesi kaunseling dijadualkan', 'tarikh_tindakan' => '2025-11-24', 'tarikh_tutup' => null, 'catatan' => null],
            ['id_isu' => 'ISU0015', 'tarikh_isu' => '2025-12-05', 'id_pelaksana' => 'SPANA_003', 'id_syarikat' => 'SPTAN_002', 'kategori_isu' => 'Isu Pematuhan', 'butiran_isu' => 'Laporan bulanan tidak lengkap', 'tahap_risiko' => 'Sederhana', 'status' => 'Baru', 'pic' => 'Muhammad Rashid', 'tindakan_diambil' => null, 'tarikh_tindakan' => null, 'tarikh_tutup' => null, 'catatan' => 'Perlu susulan'],
            ['id_isu' => 'ISU0016', 'tarikh_isu' => '2026-01-03', 'id_pelaksana' => 'SPANA_001', 'id_syarikat' => 'SPTAN_003', 'kategori_isu' => 'Kehadiran Rendah', 'butiran_isu' => 'Kehadiran purata syarikat bawah 80%', 'tahap_risiko' => 'Tinggi', 'status' => 'Baru', 'pic' => 'Hidayah Ali', 'tindakan_diambil' => null, 'tarikh_tindakan' => null, 'tarikh_tutup' => null, 'catatan' => null],
            ['id_isu' => 'ISU0017', 'tarikh_isu' => '2026-01-10', 'id_pelaksana' => 'SPANA_002', 'id_syarikat' => 'SPTAN_010', 'kategori_isu' => 'Lain-lain', 'butiran_isu' => 'Permohonan pertukaran penempatan', 'tahap_risiko' => 'Rendah', 'status' => 'Dalam Tindakan', 'pic' => 'Fatimah Idris', 'tindakan_diambil' => 'Penilaian dilakukan', 'tarikh_tindakan' => '2026-01-12', 'tarikh_tutup' => null, 'catatan' => null],
            ['id_isu' => 'ISU0018', 'tarikh_isu' => '2025-11-08', 'id_pelaksana' => 'SPANA_004', 'id_syarikat' => 'SPTAN_001', 'kategori_isu' => 'Masalah Komunikasi', 'butiran_isu' => 'Mentor tidak memberi maklumbalas berkala', 'tahap_risiko' => 'Sederhana', 'status' => 'Selesai', 'pic' => 'Nurul Hassan', 'tindakan_diambil' => 'Perbincangan dengan mentor', 'tarikh_tindakan' => '2025-11-10', 'tarikh_tutup' => '2025-11-15', 'catatan' => 'Mentor telah bersetuju'],
            ['id_isu' => 'ISU0019', 'tarikh_isu' => '2025-12-18', 'id_pelaksana' => 'SPANA_003', 'id_syarikat' => 'SPTAN_008', 'kategori_isu' => 'Bayaran Lewat', 'butiran_isu' => 'Kelewatan bayaran batch Disember', 'tahap_risiko' => 'Tinggi', 'status' => 'Dalam Tindakan', 'pic' => 'Abdul Rahman', 'tindakan_diambil' => 'Eskalasi ke kewangan', 'tarikh_tindakan' => '2025-12-19', 'tarikh_tutup' => null, 'catatan' => 'Menunggu kelulusan'],
            ['id_isu' => 'ISU0020', 'tarikh_isu' => '2026-01-20', 'id_pelaksana' => 'SPANA_001', 'id_syarikat' => 'SPTAN_006', 'kategori_isu' => 'Logbook Lewat', 'butiran_isu' => '5 graduan belum kemuka logbook Januari', 'tahap_risiko' => 'Rendah', 'status' => 'Baru', 'pic' => 'Siti Rahman', 'tindakan_diambil' => null, 'tarikh_tindakan' => null, 'tarikh_tutup' => null, 'catatan' => null],
            ['id_isu' => 'ISU0021', 'tarikh_isu' => '2026-02-01', 'id_pelaksana' => 'SPANA_002', 'id_syarikat' => 'SPTAN_005', 'kategori_isu' => 'Isu Pematuhan', 'butiran_isu' => 'Training Sesi 1 belum dimulakan', 'tahap_risiko' => 'Sederhana', 'status' => 'Baru', 'pic' => 'Ahmad Karim', 'tindakan_diambil' => null, 'tarikh_tindakan' => null, 'tarikh_tutup' => null, 'catatan' => 'Perlu perhatian segera'],
            ['id_isu' => 'ISU0022', 'tarikh_isu' => '2025-10-30', 'id_pelaksana' => 'SPANA_004', 'id_syarikat' => 'SPTAN_004', 'kategori_isu' => 'Prestasi Lemah', 'butiran_isu' => 'Graduan gagal assessment kedua', 'tahap_risiko' => 'Tinggi', 'status' => 'Selesai', 'pic' => 'Ibrahim Majid', 'tindakan_diambil' => 'Program pemulihan diadakan', 'tarikh_tindakan' => '2025-11-02', 'tarikh_tutup' => '2025-11-20', 'catatan' => 'Graduan menunjukkan peningkatan'],
            ['id_isu' => 'ISU0023', 'tarikh_isu' => '2025-11-28', 'id_pelaksana' => 'SPANA_001', 'id_syarikat' => 'SPTAN_007', 'kategori_isu' => 'Masalah Komunikasi', 'butiran_isu' => 'Laporan bulanan tidak diterima', 'tahap_risiko' => 'Rendah', 'status' => 'Ditutup', 'pic' => 'Nadia Ismail', 'tindakan_diambil' => 'Email peringatan dihantar', 'tarikh_tindakan' => '2025-11-29', 'tarikh_tutup' => '2025-12-02', 'catatan' => null],
            ['id_isu' => 'ISU0024', 'tarikh_isu' => '2026-02-10', 'id_pelaksana' => 'SPANA_003', 'id_syarikat' => 'SPTAN_009', 'kategori_isu' => 'Kehadiran Rendah', 'butiran_isu' => '3 graduan kehadiran bawah 60%', 'tahap_risiko' => 'Kritikal', 'status' => 'Baru', 'pic' => 'Razak Abdullah', 'tindakan_diambil' => null, 'tarikh_tindakan' => null, 'tarikh_tutup' => null, 'catatan' => 'Perlu eskalasi segera'],
            ['id_isu' => 'ISU0025', 'tarikh_isu' => '2025-09-30', 'id_pelaksana' => 'SPANA_002', 'id_syarikat' => 'SPTAN_001', 'kategori_isu' => 'Lain-lain', 'butiran_isu' => 'Perubahan jadual kerja tanpa notifikasi', 'tahap_risiko' => 'Rendah', 'status' => 'Ditutup', 'pic' => 'Zainab Ali', 'tindakan_diambil' => 'Makluman kepada PIC syarikat', 'tarikh_tindakan' => '2025-10-01', 'tarikh_tutup' => '2025-10-05', 'catatan' => null],
            ['id_isu' => 'ISU0026', 'tarikh_isu' => '2025-12-22', 'id_pelaksana' => 'SPANA_004', 'id_syarikat' => 'SPTAN_002', 'kategori_isu' => 'Bayaran Lewat', 'butiran_isu' => 'Elaun bulan November belum dibayar', 'tahap_risiko' => 'Kritikal', 'status' => 'Dalam Tindakan', 'pic' => 'Hidayah Rashid', 'tindakan_diambil' => 'Eskalasi ke PMO', 'tarikh_tindakan' => '2025-12-23', 'tarikh_tutup' => null, 'catatan' => 'Menunggu tindakan kewangan'],
            ['id_isu' => 'ISU0027', 'tarikh_isu' => '2026-01-15', 'id_pelaksana' => 'SPANA_001', 'id_syarikat' => 'SPTAN_008', 'kategori_isu' => 'Isu Pematuhan', 'butiran_isu' => 'Dokumen pematuhan tidak dikemaskini', 'tahap_risiko' => 'Sederhana', 'status' => 'Baru', 'pic' => 'Ali Taib', 'tindakan_diambil' => null, 'tarikh_tindakan' => null, 'tarikh_tutup' => null, 'catatan' => null],
            ['id_isu' => 'ISU0028', 'tarikh_isu' => '2025-10-12', 'id_pelaksana' => 'SPANA_003', 'id_syarikat' => 'SPTAN_005', 'kategori_isu' => 'Logbook Lewat', 'butiran_isu' => 'Batch logbook September masih pending', 'tahap_risiko' => 'Rendah', 'status' => 'Selesai', 'pic' => 'Fatimah Ali', 'tindakan_diambil' => 'Peringatan dihantar', 'tarikh_tindakan' => '2025-10-13', 'tarikh_tutup' => '2025-10-18', 'catatan' => 'Semua logbook diterima'],
            ['id_isu' => 'ISU0029', 'tarikh_isu' => '2026-02-15', 'id_pelaksana' => 'SPANA_002', 'id_syarikat' => 'SPTAN_004', 'kategori_isu' => 'Prestasi Lemah', 'butiran_isu' => 'Purata prestasi syarikat menurun', 'tahap_risiko' => 'Sederhana', 'status' => 'Baru', 'pic' => 'Muhammad Ali', 'tindakan_diambil' => null, 'tarikh_tindakan' => null, 'tarikh_tutup' => null, 'catatan' => 'Perlu analisis lanjut'],
            ['id_isu' => 'ISU0030', 'tarikh_isu' => '2026-02-20', 'id_pelaksana' => 'SPANA_004', 'id_syarikat' => 'SPTAN_010', 'kategori_isu' => 'Masalah Komunikasi', 'butiran_isu' => 'PIC syarikat tidak responsif', 'tahap_risiko' => 'Tinggi', 'status' => 'Baru', 'pic' => 'Nurul Karim', 'tindakan_diambil' => null, 'tarikh_tindakan' => null, 'tarikh_tutup' => null, 'catatan' => 'Perlu eskalasi'],
        ];

        foreach ($data as $row) {
            IsuRisiko::updateOrCreate(['id_isu' => $row['id_isu']], $row);
        }
    }
}
